---
spring:
  profiles: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/claudioed/apibol-config-files
  application:
    name: config
  rabbitmq:
      host: localhost

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8001

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/claudioed/apibol-config-files
  application:
      name: config
  rabbitmq:
      host: rabbit

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

server:
  port: 8001